version: 2

jobs:
  build:
    docker:
      - image: "lgutter/webserv_test:latest"
    steps:
      - checkout
      - run:
          name: Build
          command: 'echo Building'
      # - run:
          # name: Install curl
          # command: "apt -y install curl"
      - run:
          name: Unit-Test
          command: "make test && ./unit_test"
      - run:
          name: Acceptance-Test
          command: make acceptence

