version: 2

jobs:
  build:
    docker:
      - image: "lgutter/webserv_test:latest"
    steps:
      - checkout
      - run:
          name: Build
          command: 'echo Building'
      - run:
          name: Unit-Test
          command: "tests/unit_tests/unit_test.sh"
      - run:
          name: Acceptance-Test
          command: "tests/acceptance_tests/acceptance.sh"

