name: Criterion testing of webserv project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  build:

    name: Preparing test environment
    runs-on: rynosaurusrex/ci_for_codam:webserv

    steps:
    - name: checking out repo content
    - uses: actions/checkout@v2

    - name: Run make in tests directory
      run: make test && ./unit_test

    - name: Run Acceptence Tests
      run: make acceptence